version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
  docker: circleci/docker@1.2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: thanakijwanavit/samdocker
      - docker/push:
          digest-path: /tmp/digest.txt
          image: thanakijwanavit/samdocker
      - docker/build:
          image: thanakijwanavit/samdocker
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: thanakijwanavit/samdocker
          tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
      - run: pwd
      - run: ls -A

workflows:
  commit:
    jobs:
      - build
      - build-and-push
